name: gupit_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2
  flutter_animate: ^4.5.0
  google_maps_flutter: ^2.9.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/Gupit.png"
  min_sdk_android: 19
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/Gupit.png"

flutter:
  uses-material-design: true

  assets:

  - lib/assets/CASUAL.png
  - lib/assets/gelo.jpg
  - lib/assets/noprof.jpg
  - lib/assets/gelo2.jpg
  - lib/assets/Gupit.png
  - lib/assets/1.jpg
  - lib/assets/2.jpg
  - lib/assets/3.jpg
  - lib/assets/4.jpg
  - lib/assets/5.jpg
  - lib/assets/6.jpg
  - lib/assets/7.jpg
  - lib/assets/8.jpg
  - lib/assets/9.jpg
  - lib/assets/10.jpg
  - lib/assets/11.jpg
  - lib/assets/12.jpg
  - lib/assets/13.jpg
  - lib/assets/14.jpg
  - lib/assets/BS.jpeg
  - lib/assets/BS1.jpg
  - lib/assets/BS2.jpg
  - lib/assets/BS3.jpg
  - lib/assets/balm.jpg
  - lib/assets/clay.jpg
  - lib/assets/comb.jpg
  - lib/assets/conditioner.jpg
  - lib/assets/oil.jpg
  - lib/assets/pomade.jpg
  - lib/assets/razor.jpg
  - lib/assets/scissors.jpg
  - lib/assets/shampoo.jpg
  - lib/assets/wash.jpg
  - lib/dummydata/barbers.json
  - lib/dummydata/barbershops.json
  - lib/dummydata/products.json
